[package]
name = "secret"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]

[dependencies]
libc = "*"
bitflags = "*"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[dependencies.libsecret-sys]
path = "libsecret-sys"
