[package]
name = "secret"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]

[dependencies]
libc = "*"
glib = "*"
glib-sys = "*"
bitflags = "*"

[dependencies.libsecret-sys]
path = "libsecret-sys"
