[package]
name = "libsecret-sys"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "*"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[build-dependencies]
pkg-config = "0.3"
